export { databaseConfigFromEnv, type DatabaseConfig } from "./connection/database-config.ts";
export { closeDatabasePool, createDatabasePool, type DatabasePool } from "./connection/pool.ts";
export { withTransaction, type TransactionOptions } from "./connection/transaction.ts";
export { getClockTimestamp, getTransactionTimestamp } from "./connection/time.ts";
export { DatabaseError, normalizeDatabaseError } from "./errors/database-error.ts";
export {
  POSTGRES_SQLSTATE,
  isRetryableTransactionError,
  postgresSqlState,
  type KnownPostgresSqlState,
} from "./errors/postgres-error-codes.ts";
export { lockAccounts } from "./repositories/accounts.ts";
export {
  appendLifecycleEvent,
  validateLifecycleMetadata,
  type AppendLifecycleEvent,
  type LifecycleMetadata,
  type LifecycleMetadataKey,
  type LifecycleMetadataValue,
} from "./repositories/lifecycle-events.ts";
export {
  claimScheduledActions,
  cancelPendingScheduledActionsByDeduplicationKey,
  completeScheduledAction,
  failScheduledAction,
  insertScheduledAction,
  lockScheduledActionClaim,
  markScheduledActionStale,
  renewScheduledActionLease,
  retryScheduledAction,
  type InsertScheduledAction,
  type ScheduledAction,
} from "./repositories/scheduled-actions.ts";
export {
  claimOutboxEvents,
  deliverOutboxEvent,
  failOutboxEvent,
  insertOutboxEvent,
  renewOutboxLease,
  retryOutboxEvent,
  type InsertOutboxEvent,
  type OutboxEvent,
} from "./repositories/outbox-events.ts";
export {
  claimDeletionTargets,
  completeDeletionManifestIfReady,
  completeDeletionTarget,
  createDeletionManifest,
  createPartnershipDeletionManifestIfAbsent,
  failDeletionTarget,
  renewDeletionTargetLease,
  resumeFailedDeletionTarget,
  retryDeletionTarget,
  type CreateDeletionManifest,
  type DeletionTarget,
} from "./repositories/deletion-manifests.ts";
export type { DurableClaim } from "./types/claim.ts";
export type { QueryExecutor } from "./types/query-executor.ts";

export const databaseFoundationStatus = "f2-runtime-implemented" as const;

export {
  accountHasOccupiedPartnership,
  appendSecurityEvent,
  changeUsername,
  completeRegistrationIntent,
  consumeChallenge,
  consumeRateLimitBuckets,
  correctDateOfBirth,
  createDevice,
  createSession,
  finalizeAccountDeletionState,
  findAccountByIdentifier,
  findActiveDeviceByHandle,
  findLoginCredential,
  findSessionByVerifier,
  getAccountDeletionGeneration,
  getAccountProfile,
  getCalendarYearAfter,
  getCurrentPartnershipForAccount,
  getChallengeForDelivery,
  getPasswordHash,
  getSecurityEmailDelivery,
  insertAccount,
  insertAccountProfile,
  insertCurrentEmail,
  insertEmailChallenge,
  insertPasswordCredential,
  insertRegistrationIntent,
  insertSecurityEmailDelivery,
  isUsernameAvailable,
  isVerifiedEmailAvailable,
  listDevices,
  lockAccountForProfileMutation,
  lockAuthenticatedSession,
  lockActiveChallengeForAccount,
  lockActiveChallengeForRegistration,
  lockPendingAccountDeletion,
  lockRegistrationIntent,
  markSecurityEmailDelivered,
  recordChallengeFailure,
  recoverAccountDeletion,
  releaseCurrentEmail,
  renameDevice,
  requestAccountDeletion,
  resetRateLimitBucket,
  revokeAllSessionsForAccount,
  revokeDevice,
  revokeSession,
  rotateDeviceHandle,
  rotateSessionToken,
  scrubAccountAuthenticationData,
  supersedeActiveChallenges,
  touchSession,
  updateDisplayName,
  updatePasswordCredential,
  type AccountStatus as AuthAccountStatus,
  type AuthenticatedSession,
  type DeviceSummary,
  type EmailChallenge,
  type EmailPurpose,
  type LoginCredential,
  type RateLimitBucketInput,
  type RateLimitDecision,
  type RegistrationIntentRow,
} from "./repositories/account-auth.ts";

export {
  findDiscoverableAccountByUsername,
  type DiscoverableAccount,
} from "./repositories/partner-discovery.ts";
export {
  activeBlockExistsForPair,
  appendPartnerRequestAttempt,
  completePartnerRequestIdempotency,
  countCreatedPartnerRequestAttemptsSince,
  expirePartnerRequestsById,
  findCompletedPartnerRequestIdempotency,
  insertPartnerRequest,
  invalidatePendingRequestsForAccount,
  invalidatePendingRequestsForPair,
  latestDeclinedPartnerRequestAt,
  listActivePartnerRequests,
  loadPartnerAccountEligibility,
  loadPartnerRequestParticipants,
  lockPairPendingRequests,
  lockPartnerRequest,
  lockPartnerRequestsById,
  markPartnerRequestsAccepted,
  reservePartnerRequestIdempotency,
  setPartnerRequestCancelled,
  setPartnerRequestDeclined,
  setPartnerRequestExpired,
  type PartnerAccountEligibility,
  type PartnerRequestIdempotencyRecord,
  type PartnerRequestInvalidationReason,
  type PartnerRequestListRow,
  type PartnerRequestRecord,
  type PartnerRequestStatus,
} from "./repositories/partner-requests.ts";

export {
  insertPartnership,
  insertPartnershipMembers,
  loadPartnershipMemberIds,
  loadPartnershipReadModelForAccount,
  lockPartnershipForMetadataUpdate,
  updateRelationshipStartDateIfVersion,
  type LockedPartnershipMetadata,
  type PartnershipReadModel,
} from "./repositories/partnerships.ts";

export {
  insertAccountNotification,
  listAccountNotifications,
  markAccountNotificationRead,
  type AccountNotification,
  type AccountNotificationEventType,
} from "./repositories/account-notifications.ts";

export {
  cancelPendingScheduledActionsForAggregate,
  completeLifecycleIdempotency,
  deletePartnershipCryptoState,
  deletePartnershipRelationalContent,
  extendBreakupDeadline,
  getOpenBreakupGeneration,
  insertBreakupProcess,
  insertBreakupRestoreIntent,
  insertFormerPartnerBlock,
  insertPartnerCooldown,
  listFormerPartnerships,
  loadBreakupPartnershipId,
  loadLifecycleMemberIds,
  lockPartnershipLifecycle,
  markBreakupCancelled,
  markBreakupDissolved,
  markOpenBreakupSuperseded,
  removeFormerPartnerBlock,
  reserveLifecycleIdempotency,
  resolveExpiredPartnerEligibility,
  restorePartnership,
  setPartnershipBreakupPending,
  terminatePartnershipLifecycle,
  type FormerPartnershipRow,
  type LifecycleAccountStatus,
  type LifecycleIdempotencyRecord,
  type LifecycleState,
  type LifecycleTerminationReason,
  type LockedPartnershipLifecycle,
  type OpenBreakupProcess,
  type PartnershipDeletionOverlay,
} from "./repositories/partnership-lifecycle.ts";
