FROM node:22.18.0-bookworm-slim
ENV NODE_ENV=production
WORKDIR /app/apps/web
COPY apps/web/dist ./dist
COPY apps/web/server.mjs ./server.mjs
COPY apps/web/server-security.mjs ./server-security.mjs
COPY apps/web/proxy-security.mjs ./proxy-security.mjs
EXPOSE 4173
CMD ["node","server.mjs"]
